name: Run Karate Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Enables manual trigger from GitHub UI

jobs:
  karate-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 21 (required for running Maven and Karate)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'  # JDK 21 provided by temurin
          cache: maven

      # Install Maven
      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      # Verify if the feature file exists and list files for debugging
      - name: Verify if api_test.feature exists
        run: |
          echo "Checking if feature file exists"
          ls -al CucumberJavaProject/src/test/resources/Features/api_test.feature || echo "Feature file not found!"

      # Print current directory and list files for debugging
      - name: Print current directory and files
        run: |
          echo "Printing working directory and listing files..."
          pwd
          ls -al
          ls -al CucumberJavaProject/src/test/resources/Features

      # Run Karate Test for api_test.feature
      - name: Run Karate Test for api_test.feature
        run: |
          echo "Starting Karate tests..."
          cd CucumberJavaProject
          mvn clean test -Dtest=KarateTestRunner -X
