name: Run Cucumber Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Enables manual trigger from GitHub UI

jobs:
  cucumber-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 21 (required for running Maven and Cucumber)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'  # JDK 21 provided by temurin
          cache: maven

      # Install Maven
      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      # Verify if the feature files exist and list files for debugging
      - name: Verify feature files
        run: |
          echo "Checking if feature files exist..."
          ls -al CucumberJavaProject/src/test/resources/Features/ || echo "Feature files not found!"

      # Print current directory and list files for debugging
      - name: Print current directory and files
        run: |
          echo "Printing working directory and listing files..."
          pwd
          ls -al
          ls -al CucumberJavaProject/src/test/resources/Features

      # Run Cucumber tests using TestRunner.java
      - name: Run Cucumber Tests
        run: |
          echo "Starting Cucumber tests..."
          cd CucumberJavaProject
          mvn clean test -Dtest=TestRunner -X

      # Archive the Cucumber HTML Report
      - name: Archive Cucumber HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-reports
          path: CucumberJavaProject/target/cucumber-reports/cucumber-html-reports/overview-features.html

      # Optional: Archive the entire Cucumber report directory
      - name: Archive Full Cucumber Report Directory
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-full-reports
          path: CucumberJavaProject/target/cucumber-reports/
