name: Run Cucumber Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Enables manual trigger from GitHub UI

jobs:
  cucumber-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 17 (required for running Maven and Cucumber)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'  # Use Temurin distribution for JDK 17

      # Cache Maven dependencies to speed up builds
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Install Maven
      - name: Install Maven
        run: sudo apt-get install -y maven

      # Run the specific login.feature file using Maven
      - name: Run Cucumber Test for login.feature
        run: |
          cd CucumberJavaProject
          mvn clean test -Dcucumber.options="src/test/resources/Features/login.feature"
